export { default as Hero } from './Hero'
export { default as AboutUs } from './AboutUs'
export { default as Projects } from './Projects'
export { default as Solutions } from './Solutions'
export { default as TechStack } from './TechStack'
export { default as ContactForm } from './ContactForm'
